version: 2
jobs:
  build:
    environment:
    docker:
      - image: alpine:3.5
    working_directory: /home/ubuntu/docker-testo
    steps:
      - setup_docker_engine
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            apk add --update curl
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin 
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_BRANCH .
      - run:
          name: Run Tests
          command: docker run -it ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_BRANCH date
      - run:
          name: Push Docker Image
          command: docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
